### ISSUE TITLE
ImportError: cannot import name 'Markup' from 'flask'

### ISSUE THREAD

**Issue by RampageousRJ** [mrf345/flask_datepicker#12]
I installed and imported the latest version of Flask-Datepicker, version 0.14, but my code still doesn't run successfully and always results in an error.

Traceback (most recent call last):
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\app.py", line 1, in <module>
    from ledger import app
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\ledger\__init__.py", line 5, in <module>  
    from flask_datepicker import datepicker
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\flask_datepicker\__init__.py", line 1, in <module>
    from flask_datepicker.main import datepicker  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\flask_datepicker\main.py", line 2, in <module>
    from flask import Markup, url_for
ImportError: cannot import name 'Markup' from 'flask' (E:\Study\OneDrive - Manipal Academy of Higher Education\Coding\Mini-Projects\Arihant-Ledger\virt\Lib\site-packages\flask\__init__.py)

I tried upgrading pip and flask but I think Markup has been deprecated after Flask 2.3.0 according to the article [link](https://stackoverflow.com/questions/77249838/importerror-cannot-import-name-markup-from-flask). I would not be able to downgrade Flask as it would affect other librarires, so is there any workarounds with this?

**Comment by mrf345** [comment]
Thanks for the report, should be fixed in version 0.15
